version: "2"
services:
  kdc-server:
    build: ./kdc-server
    hostname: kdc.local
    network_mode: bridge
    env_file: kerberos.env
    volumes:
      # This is needed otherwise there won't be enough entropy to generate a new kerberos realm
      - /dev/urandom:/dev/random
    ports:
      - "749:749"
      - "88:88/udp"
